services:
  _defaults:
    autowire: true
    autoconfigure: true

  Appkweb\Bundle\EasyCrudBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  Appkweb\Bundle\EasyCrudBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']